name = "ShallowWater"
uuid = "2d049147-541f-4bea-b460-d3e5e360cd10"
authors = ["Alex Rubin <alexhrubin@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
